---
title: "Untitled"
author: "JJW"
date: "2023-01-13"
output: html_document
---


```{r}


library(dplyr)

library(tidyverse)

library(forcats)

library(ggthemes)

library(plotly)

library(knitr)

library(naniar)

library(ggplot2)

library(maps)

library(ggmap)

library(maptools)

library(sf)

library(here)

library(magrittr)
library(gridExtra)
```

```{r}
#now we'll get into the mapping, which is likely to be a major theme with this dataset
#we'll pull up our basic map iof US states first
statelines <- map_data("state")
ggplot(data = statelines) +  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + coord_fixed(1.3) + guides(fill=FALSE)
```
```{r}
#then we'll subset to out states in the ~SE that are represtned in our dataset
statelines <- map_data("state")
SE19<- subset(statelines, region %in% c("south carolina", "georgia",        "tennessee",      "virginia",       "west virginia", 
 "kentucky",       "north carolina", "florida",        "mississippi",    "kansas",        
 "maryland",       "louisiana",      "alabama",        "missouri",       "arkansas",      
"pennsylvania",   "nebraska" ))
state_outline<-ggplot(data = SE19) +  geom_polygon(aes(x = long, y = lat, fill = region, group = group), fill = "white", color="black") + coord_fixed(1.3) + guides(fill=FALSE) 

state_outline

```
```{r}
#load cleaned data
CDV_new<-   read.csv(here::here("Complete_data_CDV_vars.csv"))

glimpse(CDV_new)
```
```{r}
#to be able to join our data sets with dplyr we need to capitalise the state names from the mapping data and change the ttle of the states vaiable to region so we can properly join our datasets
SEC19 <- dplyr :: rename(SE19, State = region)
capFirst <- function(s) {paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")}

SEC19$State <- capFirst(SEC19$State)

# StFrnew <- with(CDV_new, table(State))
# STFRnew <- as.data.frame(StFrnew) 
# SECC19 <- SEC19 %>% mutate(State = recode(State, "North carolina" = "North Carolina", "South carolina" = "South Carolina", "West virginia"= "West Virginia"))
# 
# 
# dftr19 <- left_join(SECC19, STFR19)

library(viridis)


library(rgeos)

#we also want some state abbreviations we can put in the centre of our states on the map so we shall pull that data together
# statescent <- data.frame(state.center, state.abb)
# SECEnt <- subset(statescent, state.abb %in% c("PA","GA", "KS", "SC", "AR", "FL", "KY", "LA", "MD", "MS", "NC", "TN", "VA", "WV", "AL", "MO", "NE"))
```
```{r}
#we also want some major cites that we can plot on our final map
# us <- map_data("state")
# uscitiesdf <- as.data.frame(us.cities)
# Bigcities <- uscitiesdf %>% filter(pop >2000000)
```
```{r}
# library(ggrepel)
# #now we'll pull all these layers togetehr in ggplot
# SEC1 <- ggplot(data = dftr19) + 
#   geom_polygon(data = us, aes(x = long, y = lat, group = group), color ="gray50", fill = "white") + 
#   geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "gray50") + 
#   coord_fixed(1.3) + 
#   scale_fill_gradient(low = "seashell1", high = "dodgerblue4", na.value = "white", trans = "log10") 
# 
# SEC2 <- SEC1 + theme( 
#   axis.text = element_blank(),
#   axis.line = element_blank(),
#   axis.ticks = element_blank(),
#   panel.border = element_blank(),
#   panel.grid = element_blank(),
#   axis.title = element_blank(), legend.position = "right")
# 
# SEC3 <- SEC2 +  
#   geom_text(data = SECEnt, aes(x = x, y = y, label = state.abb, group = NULL, size = )) + labs(fill= "Number of cases")
# 
# SEC4 <- SEC3
# #+   geom_point(data = Bigcities, aes(x = long, y = lat), alpha = 0.5) +
#   #geom_label_repel(data = Bigcities, aes(x = long, y = lat, label = name, group = NULL))
# 
# SEC4
# 
# ggsave(here::here("results", "Figures_new", "Cases_per_State19.png"),plot = SEC4)
# 
# statetable<- table(CDV_Clean19$State)
# statetable<-as.data.frame(statetable)
# statetable
#   colnames(statetable)[1] <- "State"
#   colnames(statetable)[2] <- "No. of cases"
#   
# statetable %>% saveRDS(here::here("results", "Tables", "statetable19.rds"))
# #we also needed to recode the carolinas to capiatlise both words so we could properly join 
# #i used a log scale here as GA is massively overrrepresented and it made it difficult to percive what other states are involved
```
```{r}
#now lets look at the state maps per year using facet wrap
# StperYr19 <- with(CDV_Clean19, table(State, CollectionYear))
# SPYdf19 <- as.data.frame(StperYr19)
# spyrsttt19 <- left_join(SECC19, SPYdf19)
# SECt119 <- ggplot(data = spyrsttt19) + geom_polygon(data = us, aes(x = long, y = lat, group = group), color ="gray50", fill = "gray70") + geom_polygon(aes(x = long, y = lat, fill = Freq, group = group), color = "gray50") + coord_fixed(1.3) +  scale_fill_gradient(low = "white", high = "slateblue4", na.value = "white", trans = "log10") 
# 
# SECt219 <- SECt119 + theme( 
#   axis.text = element_blank(),
#   axis.line = element_blank(),
#   axis.ticks = element_blank(),
#   panel.border = element_blank(),
#   panel.grid = element_blank(),
#   axis.title = element_blank(), legend.position = "right")
# 
# SECt319 <- SECt219 + labs(fill= "Number of cases")
# 
# 
# SECT419 <- SECt319 + facet_wrap(~ CollectionYear)
# 
# SECT419
# 
# ggsave(here::here("results", "Figures_new", "Cases_per_State_WrapYear19.png"),plot = SECT419)

```






```{r}
library(sf)


#load counties in SE

SE_sf <- st_as_sf(map("county", regions = c("south carolina", "georgia",        "tennessee",      "virginia",       "west virginia", 
 "kentucky",       "north carolina", "florida",        "mississippi",    "kansas",        
 "maryland",       "louisiana",      "alabama",        "missouri",       "arkansas",      
"pennsylvania",   "nebraska"), plot = FALSE, fill = TRUE))


tt<-SE_sf%>% mutate(ID2=ID)

sepSE_sf<- tt %>% separate(ID, c("State", "County"), ",")


sepSE_sf$County<- capFirst(sepSE_sf$County)

sepSE_sf$State<- capFirst(sepSE_sf$State)
sepSE_sf<-sepSE_sf%>% mutate(State = recode(State, "North carolina" = "North Carolina", "South carolina" = "South Carolina", "West virginia"= "West Virginia"))%>% mutate(County=recode(County, "De kalb"="DeKalb", "Jeff davis"="Jeff Davis","Ben hill"= "Ben Hill", "Mcintosh"="McIntosh", "Mcduffie"="McDuffie"))
 
# #calculate the centroids for each county
# 
# SE_centroid <- st_centroid(sepSE_sf)
# 
# #split in to seprate long and lat coordinates
# 
# 
# SEtest4 <-  SE_centroid%>% mutate(tosplit= as.character(geom))
# 
# SEtest4$tosplit <- sub(SEtest4$tosplit, pattern = "c", replacement = "")
# 
# SEtest4$tosplit <- sub(SEtest4$tosplit, pattern = "[(]", replacement = "")
# 
# SEtest4$tosplit <- sub(SEtest4$tosplit, pattern = "[)]", replacement = "")
# 
# SEtest4$tosplit<- sub(SEtest4$tosplit, pattern = "[,]", replacement = "")
# 
# SEtest5 <- SEtest4 %>% separate(tosplit, c("long", "lat"), " ")
# 
# SE_centroid_split<- SEtest5 %>% mutate(lat = as.numeric(as.character(lat))) %>% mutate(long = as.numeric(as.character(long)))
# 
# colnames(SE_centroid_split)[6]<- "Centroid"
# 
# SE_centroid_split %>% saveRDS(here::here("data", "processed_data", "SE_centroid.rds"))
# 
# plot(sepSE_sf["State"])
```

```{r}
#join mapping data to case data
CDV_new%<>%dplyr::mutate(State = recode(State, "NC" = "North Carolina", "SC" = "South Carolina", "WV"= "West Virginia", "AR"="Arkansas","FL"="Florida","GA"="Georgia","KS"="Kansas","KY"="Kentucky","LA"="Louisiana","MO"="Missouri", "NE"="Nebraska", "PA"="Pennsylvania", "TN"="Tennessee","VA"="Virginia"))




testing123<-left_join(CDV_new, sepSE_sf, by=c("County", "State"))

testing12345<-full_join(CDV_new, sepSE_sf, by=c("County", "State"))

ggplot(testing12345)+geom_sf( aes(geometry=geom))+ geom_point(aes(x=long, y=lat, color=Species))

ttt<- as.data.frame(with(testing123,table(ID2)))

SE_freq_19<-left_join(sepSE_sf, ttt, by="ID2")

#add coords
SE_centroid_split<-as_data_frame(SE_centroid_split)

cent_SE_19<-left_join(sepSE_sf, SE_centroid_split)

cent_spec_19<- left_join(cent_SE_19,CDV_Clean19 )

#plot cases by species in SE
SESpec<- ggplot(cent_spec_19) + geom_sf(aes(geometry=geom)) +  geom_point(data = cent_spec_19, aes(x = long, y = lat, color= Species), alpha = 0.5, size= 1,position = position_jitter(width=0.05,height=0.05 ), na.rm = T)+ theme_minimal()+ scale_colour_discrete( na.translate=F ) +labs(x="Longitude", y="Latitude")
SESpec


ggsave(here::here("results", "Figures_new", "SE_AllSpec.png"),plot = SESpec)



```



```{r}


state_spec_new<-state_outline+geom_point(data=CDV_new, aes(x=long, y=lat,color=Species) )

ggsave(here::here("results","state_spec_new.png"),plot=state_spec_new)

```

```{r}

# First, you need to install the rgeos package if it's not already installed
#install.packages("rgeos")

# Load the rgeos package
library(rgeos)

# Load the map data for several states
states_map <- map_data("state",region = c("georgia", "alabama", "florida"))

spatial_data <- SpatialPointsDataFrame(SE19[, c("long", "lat")], SE19)

# Removing internal borders
states_map_simple = gSimplify(spatial_data, tol = 0.01, topologyPreserve = TRUE)

# Plot the map
plot(states_map_simple)

plot(spatial_data)

```

```{r}
# Create a list of Polygon objects
polygons <- lapply(split(SE19, SE19$region), function(x) Polygons(list(Polygon(x[, c("long", "lat")])), ID = x$region[1]))

# Create a SpatialPolygons object
sp_map <- SpatialPolygons(polygons)


# Combine polygons into a single polygon
union_map <- gUnaryUnion(sp_map,checkValidity = 2 )

# Plot the map
plot(union_map)
```

```{r}
# First, you need to install the spatstat package if it's not already installed
#install.packages("spatstat")

# Load the spatstat package
library(spatstat)

# Create a point pattern object from your data
# assuming your dataframe is called "data" and has columns "x" and "y" for coordinates

union_mapO<-as.owin(union_map)

points <- ppp(x=CDV_new$long, y=CDV_new$lat, window=union_mapO)

# Perform Ripley's K test
kest <- Kest(points, fun="Kest")

# Plot the result
plot(kest, fun="Kest", main="Ripley's K plot")

plot(union_mapO)

plot(points)


R_K<-envelope(points, fun = "Kest")

plot(R_K,main=list("Ripley's K-function for necropsy cases in mesocarnivores", cex=0.8) )
#library(here)

# png(file="RipK.jpeg",width=7, height=7)
# plot(R_K,main=list("Ripley's K-function for necropsy cases in mesocarnivores", cex=0.8) )
# dev.off()

# First, install the spatstat package if it's not already installed
#install.packages("spatstat")

# Load the spatstat package
#library(spatstat)

# Load your point pattern data
#data(meuse)

# Calculate the Ripley's K function and the envelope
k_fun <- Kest(points, correction = "translate")
#, with the correction parameter set to "translate" to account for edge effects. 
#envelope <- envelope(k_fun, fun = Kest, correction = "translate", nsim = 99)

# Plot the Ripley's K function with the envelope and error margins
plot(k_fun, col = "blue", lwd = 2)
segments(x0 = envelope$r, y0 = envelope$lower, x1 = envelope$r, y1 = envelope$upper, lty = 2, col = "gray")

```


```{r}

CDV_only<-CDV_new%>%filter(Distemper=="Y")

#repeat for cdv cases

#union_mapO<-as.owin(union_map)

points_CDV <- ppp(x=CDV_only$long, y=CDV_only$lat, window=union_mapO)

# Perform Ripley's K test
kest_CDV <- Kest(points_CDV, fun="Kest")

# Plot the result
plot(kest_CDV, fun="Kest", main="Ripley's K plot")



R_K_CDV<-envelope(points_CDV, fun = "Kest")

plot(R_K_CDV,main=list("Ripley's K-function for CDV cases in mesocarnivores", cex=0.8) )


#plot(union_mapO)

#plot(points)

# First, install the spatstat package if it's not already installed
#install.packages("spatstat")

# Load the spatstat package
#library(spatstat)

# Load your point pattern data
#data(meuse)

# Calculate the Ripley's K function and the envelope
k_fun_CDV <- Kest(points_CDV, correction = "translate")
#, with the correction parameter set to "translate" to account for edge effects. 
#envelope <- envelope(k_fun, fun = Kest, correction = "translate", nsim = 99)

# Plot the Ripley's K function with the envelope and error margins
plot(k_fun_CDV, col = "blue", lwd = 2)
segments(x0 = envelope$r, y0 = envelope$lower, x1 = envelope$r, y1 = envelope$upper, lty = 2, col = "gray")
```

```{r}

CDV_not<-CDV_new%>%filter(Distemper=="N")

#repeat for cdv cases

#union_mapO<-as.owin(union_map)

points_CDV_not <- ppp(x=CDV_not$long, y=CDV_not$lat, window=union_mapO)

# Perform Ripley's K test
kest_CDV_not <- Kest(points_CDV_not, fun="Kest")

# Plot the result
plot(kest_CDV_not, fun="Kest", main="Ripley's K plot")



R_K_CDV_not<-envelope(points_CDV_not, fun = "Kest")

plot(R_K_CDV_not,main=list("Ripley's K-function for CDV negative necropsy cases in mesocarnivores", cex=0.8) )


```
